import type {Announcement} from './announcements';
import type {Assignment, Submission, TodoItem} from './assignments';
import type {CalendarEvent} from './calendar';
import type {Course, DashboardCard} from './courses';
import type {Enrollment} from './enrollments';
import type {Module} from './modules';
import type {User, UserColors} from './users';

export const DEMO_COURSE_IDS = [128797, 130834, 128005, 124230, 130171];

export const isDemoCourseId = (courseId: number): boolean => DEMO_COURSE_IDS.includes(courseId);

export const mockDashboardCards: DashboardCard[] = [
  {
    id: 128797,
    longName: '研究会Ｂ(2)',
    shortName: '研究会Ｂ(2)',
    originalName: '5-12 秋[月2]矢作 尚久　研究会Ｂ(2) [湘南藤沢 κ16]',
    courseCode: '[月2]矢作 尚久　研究会Ｂ(2)',
    assetString: 'course_128797',
    href: '/courses/128797',
    term: '2025年度秋学期',
    subtitle: '秋学期',
    enrollmentState: 'active',
    enrollmentType: 'StudentEnrollment',
    observee: null,
    isFavorited: true,
    isK5Subject: false,
    isHomeroom: false,
    useClassicFont: false,
    canManage: false,
    canReadAnnouncements: true,
    image: null,
    color: '#4f7cff',
    position: 1,
    published: true,
    links: [],
    canChangeCoursePublishState: false,
    defaultView: 'modules',
    pagesUrl: '/courses/128797/pages',
    frontPageTitle: null,
    name: '研究会Ｂ(2)',
  },
  {
    id: 130834,
    longName: '不動産デザイン２(寄附講座)',
    shortName: '不動産デザイン２',
    originalName: '5-14 秋[月4]小林 博人　不動産デザイン２(寄附講座) [湘南藤沢 ο22]',
    courseCode: '[月4]小林 博人　不動産デザイン２',
    assetString: 'course_130834',
    href: '/courses/130834',
    term: '2025年度秋学期',
    subtitle: '秋学期',
    enrollmentState: 'active',
    enrollmentType: 'StudentEnrollment',
    observee: null,
    isFavorited: true,
    isK5Subject: false,
    isHomeroom: false,
    useClassicFont: false,
    canManage: false,
    canReadAnnouncements: true,
    image: null,
    color: '#12a87b',
    position: 2,
    published: true,
    links: [],
    canChangeCoursePublishState: false,
    defaultView: 'modules',
    pagesUrl: '/courses/130834/pages',
    frontPageTitle: null,
    name: '不動産デザイン２',
  },
  {
    id: 128005,
    longName: 'システムプログラミング基礎',
    shortName: 'システムプログラミング基礎',
    originalName: '5-41 秋[木1]楠本 博之　システムプログラミング基礎 [湘南藤沢 ε11]',
    courseCode: '[木1]楠本 博之　システムプログラミング基礎',
    assetString: 'course_128005',
    href: '/courses/128005',
    term: '2025年度秋学期',
    subtitle: '秋学期',
    enrollmentState: 'active',
    enrollmentType: 'StudentEnrollment',
    observee: null,
    isFavorited: false,
    isK5Subject: false,
    isHomeroom: false,
    useClassicFont: false,
    canManage: false,
    canReadAnnouncements: true,
    image: null,
    color: '#f0b429',
    position: 3,
    published: true,
    links: [],
    canChangeCoursePublishState: false,
    defaultView: 'modules',
    pagesUrl: '/courses/128005/pages',
    frontPageTitle: null,
    name: 'システムプログラミング基礎',
  },
  {
    id: 124230,
    longName: 'アントレプレナー概論１(寄附講座)',
    shortName: 'アントレプレナー概論１',
    originalName: '5-42 秋[木2]飯盛 崇　アントレプレナー概論１(寄附講座) [湘南藤沢 Ω22]',
    courseCode: '[木2]飯盛 崇　アントレプレナー概論１',
    assetString: 'course_124230',
    href: '/courses/124230',
    term: '2025年度秋学期',
    subtitle: '秋学期',
    enrollmentState: 'active',
    enrollmentType: 'StudentEnrollment',
    observee: null,
    isFavorited: true,
    isK5Subject: false,
    isHomeroom: false,
    useClassicFont: false,
    canManage: false,
    canReadAnnouncements: true,
    image: null,
    color: '#7c5cff',
    position: 4,
    published: true,
    links: [],
    canChangeCoursePublishState: false,
    defaultView: 'assignments',
    pagesUrl: '/courses/124230/pages',
    frontPageTitle: null,
    name: 'アントレプレナー概論１',
  },
  {
    id: 130171,
    longName: '研究会Ａ',
    shortName: '研究会Ａ',
    originalName: '5-44 秋[木4 木5]三次 仁　研究会Ａ [湘南藤沢 ι14]',
    courseCode: '[木4 木5]三次 仁　研究会Ａ',
    assetString: 'course_130171',
    href: '/courses/130171',
    term: '2025年度秋学期',
    subtitle: '秋学期',
    enrollmentState: 'active',
    enrollmentType: 'StudentEnrollment',
    observee: null,
    isFavorited: false,
    isK5Subject: false,
    isHomeroom: false,
    useClassicFont: false,
    canManage: false,
    canReadAnnouncements: true,
    image: null,
    color: '#1f9d8a',
    position: 5,
    published: true,
    links: [],
    canChangeCoursePublishState: false,
    defaultView: 'modules',
    pagesUrl: '/courses/130171/pages',
    frontPageTitle: null,
    name: '研究会Ａ',
  },
];

export const mockCourses: Course[] = mockDashboardCards.map((course) => ({
  id: course.id,
  name: course.longName,
  course_code: course.courseCode,
  start_at: '2025-09-01T00:00:00Z',
  end_at: '2026-03-31T15:00:00Z',
  term: {
    id: 43,
    name: '2025年度秋学期',
    start_at: '2025-08-31T15:00:00Z',
    end_at: '2026-03-31T15:00:00Z',
  },
  syllabus_body: `${course.longName} の前学期モック用コースです。`,
  public_description: `${course.shortName} の撮影用モックコースです。`,
}));

export const mockCourseColors: UserColors = {
  course_128797: '#4f7cff',
  course_130834: '#12a87b',
  course_128005: '#f0b429',
  course_124230: '#7c5cff',
  course_130171: '#1f9d8a',
};

export const mockAnnouncements: Announcement[] = [
  {
    id: 240277,
    title: '授業slack登録のお願い',
    message: '<p>不動産デザイナーの皆様</p><p>こちらが授業slackのリンクとなっております。</p><p>今後のアナウンスメントはこちらで行いますので登録よろしくお願いします！</p><p>10月13日（月） 上田先生による、「デザインとバリュエーション」のレクチャー、1個目の課題の概要についてです。</p>',
    posted_at: '2025-10-08T04:31:43Z',
    delayed_post_at: null,
    author: {
      id: 212611,
      display_name: '西原　大生　 NISHIHARA　TAISHO　',
      avatar_image_url: 'https://lms.keio.jp/images/messages/avatar-50.png',
    },
    context_code: 'course_130834',
    read_state: 'unread',
    html_url: 'https://lms.keio.jp/courses/130834/discussion_topics/240277',
  },
];

export const mockAssignments: Assignment[] = [
  {
    id: 1175257,
    name: '第1回課題(10月2日)',
    description: 'printf()関数の引数に自分の氏名と学籍番号を日本語で文字列として与えて表示するプログラムを作成し、Cファイルを提出してください。',
    due_at: '2025-10-07T08:00:00Z',
    points_possible: 2,
    course_id: 128005,
    html_url: 'https://lms.keio.jp/courses/128005/assignments/1175257',
    submission_types: ['online_upload'],
    has_submitted_submissions: false,
    allowed_extensions: ['c'],
    unlock_at: null,
    lock_at: null,
    assignment_group_id: 395360,
    position: 1,
    grade_group_students_individually: false,
    published: true,
  },
  {
    id: 1180843,
    name: '第1回課題：自己紹介と問題意識',
    description: '自己紹介と問題意識を各400字程度で記入してください。',
    due_at: '2025-10-08T14:59:59Z',
    points_possible: 10,
    course_id: 124230,
    html_url: 'https://lms.keio.jp/courses/124230/assignments/1180843',
    submission_types: ['online_upload'],
    has_submitted_submissions: false,
    allowed_extensions: [],
    unlock_at: null,
    lock_at: null,
    assignment_group_id: 385076,
    position: 1,
    grade_group_students_individually: false,
    published: true,
  },
  {
    id: 1183457,
    name: '第2回課題(10月9日)',
    description: 'C言語のメモリ利用に関する理解を確認するためのレポートを作成してください。',
    due_at: '2025-10-14T08:00:00Z',
    points_possible: 4,
    course_id: 128005,
    html_url: 'https://lms.keio.jp/courses/128005/assignments/1183457',
    submission_types: ['online_upload'],
    has_submitted_submissions: false,
    allowed_extensions: ['pdf'],
    unlock_at: null,
    lock_at: null,
    assignment_group_id: 395360,
    position: 1,
    grade_group_students_individually: false,
    published: true,
  },
  {
    id: 1184080,
    name: '第2回課題：講義の感想と事業テーマ',
    description: '講義の感想と、現時点で考えている事業テーマを記載してください。',
    due_at: '2025-10-15T14:59:00Z',
    points_possible: 10,
    course_id: 124230,
    html_url: 'https://lms.keio.jp/courses/124230/assignments/1184080',
    submission_types: ['online_url'],
    has_submitted_submissions: false,
    allowed_extensions: [],
    unlock_at: null,
    lock_at: '2025-10-15T14:59:59Z',
    assignment_group_id: 385076,
    position: 2,
    grade_group_students_individually: false,
    published: true,
  },
  {
    id: 1185365,
    name: '第3回課題(10月16日)',
    description: '二つの分数を入力して大小を判定するプログラムを作成してください。',
    due_at: '2025-10-21T08:00:00Z',
    points_possible: 3,
    course_id: 128005,
    html_url: 'https://lms.keio.jp/courses/128005/assignments/1185365',
    submission_types: ['online_upload'],
    has_submitted_submissions: false,
    allowed_extensions: ['c'],
    unlock_at: null,
    lock_at: null,
    assignment_group_id: 395360,
    position: 3,
    grade_group_students_individually: false,
    published: true,
  },
  {
    id: 1186062,
    name: '第3課題：チーム名、メンバー、事業内容の決定',
    description: 'チーム名、リーダー、メンバー、事業内容を決め、Slack登録を行ってください。',
    due_at: '2025-10-22T14:59:59Z',
    points_possible: 5,
    course_id: 124230,
    html_url: 'https://lms.keio.jp/courses/124230/assignments/1186062',
    submission_types: ['online_url'],
    has_submitted_submissions: false,
    allowed_extensions: [],
    unlock_at: null,
    lock_at: '2025-10-22T14:59:59Z',
    assignment_group_id: 385076,
    position: 3,
    grade_group_students_individually: false,
    published: true,
  },
];

export const mockPastAssignments: Assignment[] = [
  {
    ...mockAssignments[0],
    id: 930101,
    name: '事前アンケート',
    due_at: '2026-03-31T14:59:00Z',
    has_submitted_submissions: true,
    position: 0,
  },
];

export const mockTodoItems: TodoItem[] = mockAssignments.slice(0, 2).map((assignment) => ({
  type: 'submitting',
  assignment,
  context_type: 'Course',
  course_id: assignment.course_id,
  html_url: `https://lms.keio.jp/courses/${assignment.course_id}/assignments/${assignment.id}`,
  ignore: `https://lms.keio.jp/api/v1/users/self/todo/${assignment.id}/ignore`,
  ignore_permanently: `https://lms.keio.jp/api/v1/users/self/todo/${assignment.id}/ignore_permanently`,
}));

export const mockCalendarEvents: CalendarEvent[] = [
  ...mockAssignments.map((assignment) => {
    const course = mockDashboardCards.find((card) => card.id === assignment.course_id);

    return {
      id: `assignment_${assignment.id}`,
      title: assignment.name,
      start_at: assignment.due_at,
      end_at: assignment.due_at,
      context_code: `course_${assignment.course_id}`,
      context_name: course?.courseCode,
      workflow_state: 'active',
      html_url: assignment.html_url,
      all_day: false,
      all_day_date: null,
      type: 'assignment',
      assignment,
    } satisfies CalendarEvent;
  }),
];

export const mockModules: Module[] = [
  {
    id: 950001,
    name: 'Week 1: オリエンテーション',
    position: 1,
    unlock_at: null,
    require_sequential_progress: false,
    publish_final_grade: false,
    prerequisite_module_ids: [],
    state: 'active',
    completed_at: null,
    items_count: 2,
    items_url: 'https://lms.keio.jp/api/v1/courses/900001/modules/950001/items',
    items: [
      {
        id: 960001,
        module_id: 950001,
        position: 1,
        title: '授業計画',
        indent: 0,
        type: 'File',
        content_id: 970001,
        html_url: 'https://lms.keio.jp/courses/900001/files/970001',
        url: 'https://lms.keio.jp/api/v1/files/970001',
      },
      {
        id: 960002,
        module_id: 950001,
        position: 2,
        title: '環境構築チェック',
        indent: 0,
        type: 'Assignment',
        content_id: 930001,
        html_url: 'https://lms.keio.jp/courses/900001/assignments/930001',
        url: 'https://lms.keio.jp/api/v1/courses/900001/assignments/930001',
        content_details: {
          due_at: '2026-04-10T14:59:00Z',
          points_possible: 10,
        },
      },
    ],
  },
];

export const mockCurrentUser: User = {
  id: 980001,
  name: 'Demo Student',
  created_at: '2026-03-01T00:00:00Z',
  sortable_name: 'Student, Demo',
  short_name: 'Demo',
  avatar_url: '',
  last_name: 'Student',
  first_name: 'Demo',
  locale: 'ja',
  effective_locale: 'ja',
  permissions: {
    can_update_name: false,
    can_update_avatar: false,
    limit_parent_app_web_access: false,
  },
};

export const mockEnrollment: Enrollment = {
  id: 990001,
  course_id: 900001,
  course_section_id: 990101,
  enrollment_state: 'active',
  type: 'StudentEnrollment',
  role: 'StudentEnrollment',
  role_id: 3,
  user_id: mockCurrentUser.id,
  html_url: 'https://lms.keio.jp/courses/900001/users/980001',
  grades: {
    html_url: 'https://lms.keio.jp/courses/900001/grades/980001',
    current_score: 92,
    current_grade: 'A',
    final_score: 92,
    final_grade: 'A',
  },
  user: {
    id: mockCurrentUser.id,
    name: mockCurrentUser.name,
    sortable_name: mockCurrentUser.sortable_name,
    short_name: mockCurrentUser.short_name,
  },
  last_activity_at: '2026-04-02T06:30:00Z',
  total_activity_time: 3600,
  created_at: '2026-03-01T00:00:00Z',
  updated_at: '2026-04-02T06:30:00Z',
};

export const mockSubmissions: Submission[] = [
  {
    id: 991001,
    assignment_id: 930101,
    user_id: mockCurrentUser.id,
    submitted_at: '2026-03-30T08:00:00Z',
    grade: '9',
    score: 9,
    workflow_state: 'graded',
    late: false,
    excused: false,
    missing: false,
    late_policy_status: null,
    points_deducted: null,
    grading_period_id: null,
    assignment: mockPastAssignments[0],
  },
];
