import type {Announcement} from './announcements';
import type {Assignment, Submission, TodoItem} from './assignments';
import type {CalendarEvent} from './calendar';
import type {Course, DashboardCard} from './courses';
import type {Enrollment} from './enrollments';
import type {Module} from './modules';
import type {User, UserColors} from './users';

export const DEMO_COURSE_IDS = [900001, 900002, 900003];

export const isDemoCourseId = (courseId: number): boolean => DEMO_COURSE_IDS.includes(courseId);

export const mockDashboardCards: DashboardCard[] = [
  {
    id: 900001,
    longName: 'モバイルアプリケーション開発',
    shortName: 'モバイル開発',
    originalName: 'モバイルアプリケーション開発',
    courseCode: 'APP101',
    assetString: 'course_900001',
    href: '/courses/900001',
    term: '2026 Spring',
    subtitle: '春学期',
    enrollmentState: 'active',
    enrollmentType: 'StudentEnrollment',
    observee: null,
    isFavorited: true,
    isK5Subject: false,
    isHomeroom: false,
    useClassicFont: false,
    canManage: false,
    canReadAnnouncements: true,
    image: null,
    color: '#4f7cff',
    position: 1,
    published: true,
    links: [],
    canChangeCoursePublishState: false,
    defaultView: 'modules',
    pagesUrl: '/courses/900001/pages',
    frontPageTitle: null,
    name: 'モバイル開発',
  },
  {
    id: 900002,
    longName: '情報デザイン演習',
    shortName: '情報デザイン',
    originalName: '情報デザイン演習',
    courseCode: 'DES204',
    assetString: 'course_900002',
    href: '/courses/900002',
    term: '2026 Spring',
    subtitle: '春学期',
    enrollmentState: 'active',
    enrollmentType: 'StudentEnrollment',
    observee: null,
    isFavorited: true,
    isK5Subject: false,
    isHomeroom: false,
    useClassicFont: false,
    canManage: false,
    canReadAnnouncements: true,
    image: null,
    color: '#12a87b',
    position: 2,
    published: true,
    links: [],
    canChangeCoursePublishState: false,
    defaultView: 'modules',
    pagesUrl: '/courses/900002/pages',
    frontPageTitle: null,
    name: '情報デザイン',
  },
  {
    id: 900003,
    longName: 'データ分析入門',
    shortName: 'データ分析',
    originalName: 'データ分析入門',
    courseCode: 'DAT110',
    assetString: 'course_900003',
    href: '/courses/900003',
    term: '2026 Spring',
    subtitle: '春学期',
    enrollmentState: 'active',
    enrollmentType: 'StudentEnrollment',
    observee: null,
    isFavorited: false,
    isK5Subject: false,
    isHomeroom: false,
    useClassicFont: false,
    canManage: false,
    canReadAnnouncements: true,
    image: null,
    color: '#f0b429',
    position: 3,
    published: true,
    links: [],
    canChangeCoursePublishState: false,
    defaultView: 'modules',
    pagesUrl: '/courses/900003/pages',
    frontPageTitle: null,
    name: 'データ分析',
  },
];

export const mockCourses: Course[] = mockDashboardCards.map((course) => ({
  id: course.id,
  name: course.longName,
  course_code: course.courseCode,
  start_at: '2026-04-01T00:00:00Z',
  end_at: '2026-07-31T00:00:00Z',
  syllabus_body: `${course.longName} のサンプルシラバスです。`,
  public_description: `${course.shortName} の画面確認用ダミーコースです。`,
}));

export const mockCourseColors: UserColors = {
  course_900001: '#4f7cff',
  course_900002: '#12a87b',
  course_900003: '#f0b429',
};

export const mockAnnouncements: Announcement[] = [
  {
    id: 910001,
    title: '初回授業の資料を公開しました',
    message: '第1回の講義資料を公開しました。',
    posted_at: '2026-03-25T09:00:00Z',
    delayed_post_at: null,
    author: {
      id: 920001,
      display_name: 'Demo Teacher',
      avatar_image_url: '',
    },
    context_code: 'course_900001',
    read_state: 'unread',
    html_url: 'https://lms.keio.jp/courses/900001/discussion_topics/910001',
  },
  {
    id: 910002,
    title: '履修者向けガイダンスのお知らせ',
    message: '授業開始前のガイダンス情報です。',
    posted_at: '2026-03-27T09:00:00Z',
    delayed_post_at: null,
    author: {
      id: 920002,
      display_name: 'Demo Staff',
      avatar_image_url: '',
    },
    context_code: 'course_900002',
    read_state: 'read',
    html_url: 'https://lms.keio.jp/courses/900002/discussion_topics/910002',
  },
];

export const mockAssignments: Assignment[] = [
  {
    id: 930001,
    name: '環境構築チェック',
    description: '開発環境のセットアップ状況を提出してください。',
    due_at: '2026-04-10T14:59:00Z',
    points_possible: 10,
    course_id: 900001,
    submission_types: ['online_text_entry'],
    has_submitted_submissions: false,
    allowed_extensions: [],
    unlock_at: null,
    lock_at: null,
    assignment_group_id: 940001,
    position: 1,
    grade_group_students_individually: false,
    published: true,
  },
  {
    id: 930002,
    name: 'UI観察メモ',
    description: '身近なアプリのUI観察メモを提出してください。',
    due_at: '2026-04-17T14:59:00Z',
    points_possible: 20,
    course_id: 900002,
    submission_types: ['online_upload'],
    has_submitted_submissions: false,
    allowed_extensions: ['pdf'],
    unlock_at: null,
    lock_at: null,
    assignment_group_id: 940002,
    position: 1,
    grade_group_students_individually: false,
    published: true,
  },
  {
    id: 930003,
    name: 'データ可視化ミニレポート',
    description: '指定データを可視化し、短い考察を提出してください。',
    due_at: '2026-04-24T14:59:00Z',
    points_possible: 30,
    course_id: 900003,
    submission_types: ['online_upload'],
    has_submitted_submissions: false,
    allowed_extensions: ['pdf', 'ipynb'],
    unlock_at: null,
    lock_at: null,
    assignment_group_id: 940003,
    position: 1,
    grade_group_students_individually: false,
    published: true,
  },
];

export const mockPastAssignments: Assignment[] = [
  {
    ...mockAssignments[0],
    id: 930101,
    name: '事前アンケート',
    due_at: '2026-03-31T14:59:00Z',
    has_submitted_submissions: true,
    position: 0,
  },
];

export const mockTodoItems: TodoItem[] = mockAssignments.slice(0, 2).map((assignment) => ({
  type: 'submitting',
  assignment,
  context_type: 'Course',
  course_id: assignment.course_id,
  html_url: `https://lms.keio.jp/courses/${assignment.course_id}/assignments/${assignment.id}`,
  ignore: `https://lms.keio.jp/api/v1/users/self/todo/${assignment.id}/ignore`,
  ignore_permanently: `https://lms.keio.jp/api/v1/users/self/todo/${assignment.id}/ignore_permanently`,
}));

export const mockCalendarEvents: CalendarEvent[] = [
  {
    id: 920101,
    title: 'モバイル開発 第1回',
    start_at: '2026-04-08T01:00:00Z',
    end_at: '2026-04-08T02:30:00Z',
    context_code: 'course_900001',
    context_name: 'APP101',
    workflow_state: 'active',
    html_url: 'https://lms.keio.jp/calendar?event_id=920101',
    all_day: false,
    all_day_date: null,
    type: 'event',
  },
  {
    id: `assignment_${mockAssignments[0].id}`,
    title: mockAssignments[0].name,
    start_at: mockAssignments[0].due_at,
    end_at: mockAssignments[0].due_at,
    context_code: 'course_900001',
    context_name: 'APP101',
    workflow_state: 'active',
    html_url: `https://lms.keio.jp/courses/${mockAssignments[0].course_id}/assignments/${mockAssignments[0].id}`,
    all_day: false,
    all_day_date: null,
    type: 'assignment',
    assignment: mockAssignments[0],
  },
  {
    id: `assignment_${mockAssignments[1].id}`,
    title: mockAssignments[1].name,
    start_at: mockAssignments[1].due_at,
    end_at: mockAssignments[1].due_at,
    context_code: 'course_900002',
    context_name: 'DES204',
    workflow_state: 'active',
    html_url: `https://lms.keio.jp/courses/${mockAssignments[1].course_id}/assignments/${mockAssignments[1].id}`,
    all_day: false,
    all_day_date: null,
    type: 'assignment',
    assignment: mockAssignments[1],
  },
];

export const mockModules: Module[] = [
  {
    id: 950001,
    name: 'Week 1: オリエンテーション',
    position: 1,
    unlock_at: null,
    require_sequential_progress: false,
    publish_final_grade: false,
    prerequisite_module_ids: [],
    state: 'active',
    completed_at: null,
    items_count: 2,
    items_url: 'https://lms.keio.jp/api/v1/courses/900001/modules/950001/items',
    items: [
      {
        id: 960001,
        module_id: 950001,
        position: 1,
        title: '授業計画',
        indent: 0,
        type: 'File',
        content_id: 970001,
        html_url: 'https://lms.keio.jp/courses/900001/files/970001',
        url: 'https://lms.keio.jp/api/v1/files/970001',
      },
      {
        id: 960002,
        module_id: 950001,
        position: 2,
        title: '環境構築チェック',
        indent: 0,
        type: 'Assignment',
        content_id: 930001,
        html_url: 'https://lms.keio.jp/courses/900001/assignments/930001',
        url: 'https://lms.keio.jp/api/v1/courses/900001/assignments/930001',
        content_details: {
          due_at: '2026-04-10T14:59:00Z',
          points_possible: 10,
        },
      },
    ],
  },
];

export const mockCurrentUser: User = {
  id: 980001,
  name: 'Demo Student',
  created_at: '2026-03-01T00:00:00Z',
  sortable_name: 'Student, Demo',
  short_name: 'Demo',
  avatar_url: '',
  last_name: 'Student',
  first_name: 'Demo',
  locale: 'ja',
  effective_locale: 'ja',
  permissions: {
    can_update_name: false,
    can_update_avatar: false,
    limit_parent_app_web_access: false,
  },
};

export const mockEnrollment: Enrollment = {
  id: 990001,
  course_id: 900001,
  course_section_id: 990101,
  enrollment_state: 'active',
  type: 'StudentEnrollment',
  role: 'StudentEnrollment',
  role_id: 3,
  user_id: mockCurrentUser.id,
  html_url: 'https://lms.keio.jp/courses/900001/users/980001',
  grades: {
    html_url: 'https://lms.keio.jp/courses/900001/grades/980001',
    current_score: 92,
    current_grade: 'A',
    final_score: 92,
    final_grade: 'A',
  },
  user: {
    id: mockCurrentUser.id,
    name: mockCurrentUser.name,
    sortable_name: mockCurrentUser.sortable_name,
    short_name: mockCurrentUser.short_name,
  },
  last_activity_at: '2026-04-02T06:30:00Z',
  total_activity_time: 3600,
  created_at: '2026-03-01T00:00:00Z',
  updated_at: '2026-04-02T06:30:00Z',
};

export const mockSubmissions: Submission[] = [
  {
    id: 991001,
    assignment_id: 930101,
    user_id: mockCurrentUser.id,
    submitted_at: '2026-03-30T08:00:00Z',
    grade: '9',
    score: 9,
    workflow_state: 'graded',
    late: false,
    excused: false,
    missing: false,
    late_policy_status: null,
    points_deducted: null,
    grading_period_id: null,
    assignment: mockPastAssignments[0],
  },
];
